################################ Default configuration ###################
baseURL = "https://qleap-edu-keio.github.io/"
title = "QLEAP Education - Keio University"
theme = "meghna-hugo"
themesDir = "../.."
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "About"
pre = "#"
url = "cta"
weight = 1

#[[Languages.en.menu.main]]
#name = "services"
#pre = "#"
#url = "services"
#weight = 2

#[[Languages.en.menu.main]]
#name = "portfolio"
#pre = "#"
#url = "portfolio"
#weight = 3

[[Languages.en.menu.main]]
name = "Other Participating Organizations"
pre = "#"
url = "team"
weight = 4

#[[Languages.en.menu.main]]
#name = "pricing"
#pre = "#"
#url = "pricing"
#weight = 5

[[Languages.en.menu.main]]
name = "News"
pre = "#"
url = "blog"
weight = 6

[[Languages.en.menu.main]]
name = "Keio University Quantum Computing Center"
pre = ""
url = "https://quantum.keio.ac.jp/"
weight = 7 

[[Languages.en.menu.main]]
name = "Advancing Quantum Architecture Research Group"
pre = ""
url = "https://aqua.sfc.wide.ad.jp/"
weight = 8 

[[Languages.en.menu.main]]
name = "Online Lecture"
pre = ""
url = "https://q-leap.lms.nii.ac.jp/auth/shibboleth/login.php"
weight = 9 

[[Languages.en.menu.main]]
name = "Educational Material Database"
pre = ""
url = "https://qacademy.jp/material/"
weight = 10 

[[Languages.en.menu.main]]
name = "Contact"
pre = "#"
url = "contact"
weight = 11 



################### Japanese Navigation ########################
[[Languages.jp.menu.main]]
name = "私たちについて"
pre = "#"
url = "cta"
weight = 1

#[[Languages.jp.menu.main]]
#name = "service"
#pre = "#"
#url = "services"
#weight = 2

#[[Languages.jp.menu.main]]
#name = "ポートフォリオ"
#pre = "#"
#url = "portfolio"
#weight = 3

[[Languages.jp.menu.main]]
name = "他の参加機関"
pre = "#"
url = "team"
weight = 4

#[[Languages.jp.menu.main]]
#name = "tarification"
#pre = "#"
#url = "pricing"
#weight = 5

[[Languages.jp.menu.main]]
name = "ニュース"
pre = "#"
url = "blog"
weight = 6

[[Languages.jp.menu.main]]
name = "慶應義塾大学量子コンピューティングセンター"
pre = ""
url = "https://quantum.keio.ac.jp/"
weight = 7 

[[Languages.jp.menu.main]]
name = "先進的量子アーキテクチャ"
pre = ""
url = "https://aqua.sfc.wide.ad.jp/"
weight = 8 

[[Languages.jp.menu.main]]
name = "オンライン講義"
pre = ""
url = "https://q-leap.lms.nii.ac.jp/auth/shibboleth/login.php"
weight = 9 

[[Languages.jp.menu.main]]
name = "教材データベース"
pre = ""
url = "https://qacademy.jp/material/"
weight = 10 

[[Languages.jp.menu.main]]
name = "連絡先"
pre = "#"
url = "contact"
weight = 11 


############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Responsive Multipurpose Parallax Hugo Template"
author = "Themefisher"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

############################# social icons ##########################
#[[params.social]]
#icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
#link = "#"

#[[params.social]]
#icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
link = "#"

#[[params.social]]
#icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
#link = "#"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; QLEAP Education Project Keio University"

################################ Japanese Language ########################
[Languages.jp]
languageName = "Ja"
languageCode = "ja-jp"
contentDir = "content/japanese"
weight = 2
home = "Accueil"
copyright = "Copyright &copy; 量子技術高等教育拠点 慶應義塾大学"
